---
title: "Homework"
output: html_document
---

```{r child = "_timeline.Rmd", include=FALSE}
```

```{r child = "_list_of_hw.Rmd", include=FALSE}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(kableExtra)
```

All homework assignments should be emailed to the instructor at `scheuerl@uw.edu` with the subject line `FISH 521 - HW?` where `?` is the assignment number.

```{r week_hw, include = FALSE}
## empty list for labs
week_hw <- vector("list", 10)
names(week_hw) <- paste0("L", seq(10))
## hw topics
week_hw$L1 <- focal_paper
week_hw$L2 <- message_box
week_hw$L3 <- holiday_1
week_hw$L4 <- proposal_draft
week_hw$L5 <- cover_letter
week_hw$L6 <- review_draft
week_hw$L7 <- scicomm
week_hw$L8 <- holiday_2
week_hw$L9 <- proposal_final
week_hw$L10 <- review_final
```

```{r topics, include = FALSE}
topics <- lapply(week_hw, function(x) { if(is.list(x)) {c(x$topics)} else {""} })
## topics formatted for html
topics_html <- sapply(lapply(topics, paste, "<br>", collapse = ""), c)
names(topics_html) <- NULL
```

```{r assignment_links, include = FALSE}
assignment_links <- lapply(week_hw, function(x) { if(is.list(x)) {c(x$html)} else {""} })
assignment_links_html <- sapply(lapply(assignment_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-alt", height = "2em", fill = "#2fa4e7")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-alt", height = "2em", fill = "#2fa4e7")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse="<br>"); tmp}), c)
```

```{r template_links, include = FALSE}
template_links <- lapply(week_hw, function(x) { if(is.list(x)) {c(x$rmd)} else {""} })
template_links_html <- sapply(lapply(template_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-code", height = "2em", fill = "#2fa4e7")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-code", height = "2em", fill = "#2fa4e7")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse="<br>"); tmp}), c)
```

```{r data_links, include = FALSE}
data_links <- lapply(week_hw, function(x) { if(is.list(x)) {x$data} else {""} })
data_links_html <- sapply(lapply(data_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("table", height = "2em", fill = "#2fa4e7")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("table", height = "2em", fill = "#2fa4e7")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse="<br>"); tmp}), c)
```

```{r key_links, include = FALSE}
key_links <- lapply(week_hw, function(x) { if(is.list(x)) {c(x$key)} else {""} })
key_links_html <- sapply(lapply(key_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("key", height = "2em", fill = "#2fa4e7")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("key", height = "2em", fill = "#2fa4e7")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = " ")
  tmp}), c)
names(key_links_html) <- NULL
```

```{r percents, include = FALSE}
percents <- lapply(week_hw, function(x) { if(is.list(x)) {c(x$percent)} else {""} })
## due dates formatted for html
percents_html <- sapply(lapply(percents, paste, "<br>", collapse = ""), c)
names(percents_html) <- NULL
```

```{r due_dates, include = FALSE}
due_dates <- lapply(week_hw, function(x) { if(is.list(x)) {c(x$due_date)} else {""} })
## due dates formatted for html
due_dates_html <- sapply(lapply(due_dates, paste, "<br>", collapse = ""), c)
names(due_dates_html) <- NULL
```

```{r generate_table, echo=FALSE}
## data frame with dates & topics
syl_txt <- data.frame(
  date = sub("0(\\d)", "\\1", format(mon[1:10], "%d %b")),
  topics = topics_html,
  percents = percents_html,
  assignment_links = assignment_links_html,
  # template_links = template_links_html,
  due_dates = due_dates_html
  # key_links = key_links_html
)
colnames(syl_txt) <- c("Date", "Topic", "Grade", "Instructions", "Due date")
rownames(syl_txt) <- NULL

## generate table
kable(syl_txt, format = "html", caption = " ",
      align = "clccc", escape = FALSE) %>%
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE,
                position = "left") %>%
  column_spec(1, width = "6em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(c(3, 4, 5), width = "8em")
```

