---
title: "Finding an interesting paper"
subtitle: "Homework #1"
author: "FISH 521 - Proposal Writing and Professional Development"
date: "8 January 2024"
output:
  html_document:
    theme: cerulean
    highlight: textmate
    toc: false
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

## Task 1

Use some form of database search engine (or word of mouth) to find a scientific (focal) paper of interest that was published in 2016 or earlier. Provide the complete citation for the paper.

## Task 2

Write down 3 things you like about the paper and 3 things you would have done differently (eg, less technical language, writing style, layout/organization, use of tables and figures, design of tables or figures).

## Task 3

Provide the citations for 5 papers that your focal paper cited that you are interested in reading and learning more about.

## Taks 4

Provide the citations for 5 papers that cited your focal paper and that you are interested in reading and learning more about. (Note: if your focal paper has not yet been cited 5+ times, indicate as much and list all of those that have cited it.)

