---
title: "Student presentations"
subtitle: "Homework #7"
author: "FISH 521 - Proposal Writing and Professional Development"
date: "28 February 2022"
output:
  html_document:
    theme: cerulean
    highlight: textmate
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

## Background

Your assignment this week is to give a live presentation of your proposal idea **in class** on February 28. Your presentation should cover the following elements:

* background and rationale for your proposed research

* questions of interest (or hypotheses to test)

* methods/approach

* anticipated results

* implications (intellectual merit)


## Evaluation rubric

Mark will evaluate the quality of your presentation based on the following criteria:

* Title slide with name, affiliation, and contact info

* Acknowledgment of collaborators and funders

* Layout/design of the slides (eg, good color contrast, appropriate font size)

* Speaking clearly and addressing the audience rather than the computer or slides

* Presenting the background and clear rationale for the study

* Brief explanation of the methods or approach

* Highlighting expected results and any potential difficulties

* Brief comment(s) on the implications of the research

* Appropriate ending

## Schedule




